name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Read version from __version__.txt
      id: read_version
      run: echo "::set-output name=version::$(cat version.txt)"


    - name: Build and push Docker image with timestamp tag
      uses: docker/build-push-action@v4.1.1
      with:
        push: true
        tags: raushanraja/jammybase:latest, raushanraja/jammybase:${{ steps.read_version.outputs.version }}


